__include__: [
  '../dataset/visdrone_detection.yml',
  '../runtime.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]


output_dir: ./output/rtdetrv2_r18vd_60e_visdrone


PResNet:
  depth: 18
  freeze_at: -1
  freeze_norm: False
  pretrained: True


HybridEncoder:
  in_channels: [128, 256, 512]
  hidden_dim: 256
  expansion: 0.5
  use_encoder_idx: [2]
  num_encoder_layers: 1


RTDETRTransformerv2:
  num_layers: 3


RTDETRCriterionv2:
  num_classes: 10
  matcher:
    weight_dict: {cost_class: 2, cost_bbox: 5, cost_giou: 2}
    alpha: 0.25
    gamma: 2.0


epoches: 60
